baseURL: "https://dfer.io/presentaciones/hacking-uart"
languageCode: "es-es"
title: "Hacking UART for fun and profit"
theme: "hugo-theme-revealjs"
params:
    reveal_theme: black
    revealjs:
        controls: true
        progress: true
        history: true
        center: true
        height: 100%
        width: 100%
        slideNumber: true
        transitionSpeed: 'fast'
        autoPlayMedia: true
